- targets:
    - 198.18.20.11:9100
    - 198.18.20.12:9100
    - 198.18.20.20:9100
    - 198.18.22.11:9100
    - 198.18.22.12:9100
    - 198.18.22.13:9100
  labels:
    source: fake_categraf_future
    monitor: basic_resource
- targets:
    - 198.18.20.11:8081
    - 198.18.20.12:8081
  labels:
    source: fake_categraf_future
    monitor: jvm_app
    application: order-service
- targets:
    - 198.18.20.20:80
  labels:
    source: fake_categraf_future
    monitor: nginx
- targets:
    - 198.18.20.20:6379
  labels:
    source: fake_categraf_future
    monitor: redis
- targets:
    - 198.18.22.11:1521
    - 198.18.22.12:1521
    - 198.18.22.13:1521
  labels:
    source: fake_categraf_future
    monitor: oracle
